name: "Update Providers"
on:
  push:
    branches: 
     - update-providers
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_providers:
    name: "Update Providers"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: yarn install & yarn add ts-node
        run: |
          yarn install
          yarn global add ts-node

      - name: Update providers
        run: |
            ts-node ./.github/scripts/update-providers.ts
            shopt -s extglob
            mv .git git1
            mv .github git2
            rm .??*
            mv  git1 .git
            rm -rf !("providers.json")

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: update-providers
          commit_message: "chore: update providers"
          skip_fetch: false
          push_options: '--force'
          create_branch: true

